Blogsystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('blogapp.urls')),
    path('inbox/notifications/', include("notifications.urls", namespace='notifications')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import homeView, postBlog_view, blogList_view, blogDetail_view, update_View, update_comment_View, \
    delete_post_view, uploadProfile_view, profile_view, about_view

app_name = 'blogapp'

urlpatterns = [
    path('', homeView, name='home'),
    path('blog-view/', login_required(postBlog_view), name='blog'),
    path('blog-list/', blogList_view, name='blogDetail'),
    path('blogs/category/<str:category>/', blogList_view, name='blog_list_category'),
    path('blog-deatil/<int:post_id>/', login_required(blogDetail_view), name='fullDetail'),
    path('update/<int:comment_id>/', update_View, name='update'),
    path('update/update-comment/<int:comment_id>/', update_comment_View, name='updateComment'),
    path('delete/<int:delete_id>/', delete_post_view, name='delete'),
    path('profile/', uploadProfile_view, name='profile'),
    path('profile-view/', profile_view, name='profile_view'),
    path('about-us/', about_view, name='about_us'),

]

blogapp/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Post(TimeStampedModel):
    title = models.CharField(max_length=200, null=True)
    blog = RichTextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    photos = models.ImageField(upload_to='Upload_images/')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


class Category(TimeStampedModel):
    name = models.CharField(max_length=225)

    def __str__(self):
        return self.name


class Comment(TimeStampedModel):
    commented_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    comment = models.TextField()
    post = models.ForeignKey('Post', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.comment[:20]


class UserProfile(TimeStampedModel):
    user_profile = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    mobile_number = models.CharField(max_length=225)
    address = models.TextField()
    photos = models.ImageField(upload_to='user_profile/')

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes', null=True)

blogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, Category, Comment, UserProfile
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.admin.views.decorators import staff_member_required


def homeView(request):
    return render(request, 'home.html')


def login(request):
    print(request.user.user_name)
    return render(request, 'login.html')


def postBlog_view(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        blog = request.POST.get('blog')
        photos = request.FILES.get('images')
        category_id = request.POST.get('category')
        category = Category.objects.get(id=category_id)
        created_by = request.user
        instance = Post.objects.create(
            title=title,
            blog=blog,
            photos=photos,
            category=category,
            created_by=request.user
        )
        instance.save()
        return redirect('/blog-list')
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'postblog.html', context)


def blogList_view(request, category=None):
    search_post = request.GET.get('search')
    posts = Post.objects.all().order_by('-created')
    if search_post:
        posts = Post.objects.filter(Q(title__icontains=search_post) | Q(category__name__icontains=search_post))
    if category:
        posts = Post.objects.filter(category__name=category)

    paginator = Paginator(posts, 3)
    page_num = request.GET.get('page')
    final_data = paginator.get_page(page_num)
    categories = Category.objects.all()
    blog = Post.objects.all().order_by('-created')[:3]
    context = {
        "post": final_data,
        'categories': categories,
        'blogs': blog
    }
    return render(request, 'blog_list.html', context)


def blogDetail_view(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        commented_by = request.user
        comment_text = request.POST.get('msg')
        comment = Comment.objects.create(
            commented_by=request.user,
            comment=comment_text,
            post=post,
        )
        comment.save()
        return HttpResponseRedirect(request.path_info)

    comments = Comment.objects.filter(post=post)
    context = {
        'object': post,
        'comments': comments,
    }
    return render(request, 'blog_detail.html', context)


def update_View(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    context = {
        'comment': comment
    }
    return render(request, 'update_comment.html', context)


def update_comment_View(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user != comment.commented_by:
        return render(request, 'unauthorized_access.html')
    else:
        if request.method == 'POST':
            comment_text = request.POST.get('msg')
            comment.comment = comment_text
            comment.save()
            return redirect(reverse('blogapp:fullDetail', kwargs={'post_id': comment.post.id}))
    return render(request, 'update_comment.html', {'comment': comment})


def delete_post_view(request, delete_id):
    post_delete = Post.objects.get(id=delete_id)
    post_delete.delete()
    return redirect('/blog-list')


def uploadProfile_view(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        mobile_number = request.POST.get('mobile')
        address = request.POST.get('address')
        photos = request.FILES.get('images')
        user_profile = request.user
        instance, created = UserProfile.objects.get_or_create(
            user_profile=user_profile,
            defaults={'name': name, 'mobile_number': mobile_number, 'address': address, 'photos': photos}
        )
        return redirect('/profile-view')
    return render(request, 'profile.html')


def profile_view(request):
    user = request.user
    if user.is_authenticated:
        try:
            user_profile = UserProfile.objects.get(user_profile=user)
            context = {'final_data': user_profile}
            return render(request, 'profile_view.html', context)
        except UserProfile.DoesNotExist:
            return redirect('blogapp:profile')
    else:
        return redirect('login')


def about_view(request):
    return render(request, 'about_us.html')

blogapp/templates/base.html
<!DOCTYPE html>{% load static %} {% load notifications_tags %}
<html lang="en">
<head>

    <title>{% block title %} {% endblock %}</title>

    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>

    {% if request.user.is_authenticated %}
    {% register_notify_callbacks
    callbacks='fill_notification_list,fill_notification_badge,fetchNotificationsReadAndUnreadList' %}
    {% endif %}
    {% block meta %} {% endblock %}
</head>
<body>
<section>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top ">
        <div class="container">
            <a class="navbar-brand text-light" href="{% url 'blogapp:home'%}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if request.user.is_authenticated %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-light" href="{% url 'blogapp:blogDetail' %}">Blogs</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-light" href="{% url 'blogapp:about_us'%}"> About Us</a>
                    </li>
                    <li class="nav-item dropdown mx-2">
                        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                           style="padding:0"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ image.photos.url }}"
                                 width="40" height="40" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'blogapp:profile_view' %}">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-light" href="{% url 'blogapp:blogDetail' %}">Blogs</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-light" href="{% url 'account_signup' %}">Signup</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'account_login' %}">Login</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
</section>
<section>
    <div class="m-auto mt-5 slider">
        {% block body %}
        {% endblock %}
    </div>
</section>
</body>
<section>
    <footer class="bg-body-tertiary text-center text-lg-start bg-primary">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
            © 2023 Copyright:
            <a class="text-body text-decoration-none" href="{% url  'blogapp:home'%}">Blog_Application</a>
        </div>
    </footer>
</section>
<!---->
</html>

blogapp/templates/blog_detail.html
{% extends 'base.html' %}

{% block title %} Blog Detail{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12 m-auto   mt-3 left  top ">
            <div class="card-body ">
                <h1> {{ object.title }}</h1>
                <ul class="list-unstyled">
                    <li>
                        <div class="col-lg-8">
                            <h6 class="mb-0"> {{ object.created_by }} </h6>
                            <small class="text-body-secondary">Published in <b>{{object.category.name}}</b> &nbsp.&nbsp
                                {{object.created.date }} </small>
                        </div>
                    </li>
                </ul>

                <img src="{{ object.photos.url }}" alt="{{ object.title }} " class="card-img-top"
                     style="height: 510px;">

                <p class="card-text mt-3 mb-3 ">{{ object.blog | safe}}</p>
            </div>
        </div>
        <div class=" col-md-6  offset-md-1 offset-sm-1 col-12 mt-4">
            <form method="post" enctype="multipart/form-data" action="{% url 'blogapp:fullDetail' post_id=object.id %}">
                {% csrf_token %}
                <h3>Leave a comment:</h3>
                <div class="form-group">
                    <label for="message" class="my-2 fw-bold">Comment</label>
                    <textarea name="msg" id="message" cols="30" rows="5" class="form-control"
                              placeholder="leave a comment"></textarea>
                </div>
                <div class="form-group text-end">
                    <button type="submit" class="btn btn-primary my-2">Post</button>
                </div>
            </form>
        </div>
        <div class="col-md-8 col-xl-6">
            {% for comment in comments %}
            <div class="card mb-3">
                <div class="card-body">
                    <div class="d-flex flex-start align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-standing-dress rounded-circle shadow-1-strong me-3"
                             viewBox="0 0 16 16">
                            <path d="M8 3a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m-.5 12.25V12h1v3.25a.75.75 0 0 0 1.5 0V12h1l-1-5v-.215a.285.285 0 0 1 .56-.078l.793 2.777a.711.711 0 1 0 1.364-.405l-1.065-3.461A3 3 0 0 0 8.784 3.5H7.216a3 3 0 0 0-2.868 2.118L3.283 9.079a.711.711 0 1 0 1.365.405l.793-2.777a.285.285 0 0 1 .56.078V7l-1 5h1v3.25a.75.75 0 0 0 1.5 0Z"/>
                        </svg>
                        <div>
                            <h6 class="fw-bold text-primary mb-1">
                                {{comment.commented_by}}
                                <a href="{% url 'blogapp:updateComment' comment.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                                    </svg>
                                </a>
                            </h6>
                            <p class="text-muted small mb-0">{{comment.created}}</p>
                        </div>
                    </div>
                    <p class="mt-3 mb-4 pb-2">{{comment.comment}}</p>
                    <div class="small d-flex justify-content-start">
                        <a href="{% url 'blogapp:updateComment' comment.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-heart" viewBox="0 0 16 16">
                                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                            </svg>
                        </a>
                        <a href="#myModal" style="margin-left: 10px" data-bs-toggle="modal"
                           data-bs-target="#exampleModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-chat" viewBox="0 0 16 16">
                                <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="d-flex align-items-center">
                            <img src="{{ image.photos.url }}"
                                 alt="Ritik Yadav" class="rounded-circle me-2" width="32" height="32">
                            <p class="m-0">{{ request.user.username }}</p>
                        </div>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="message-text" class="col-form-label">Message:</label>
                            <textarea class="form-control" id="message-text"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Send message</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{%endblock%}

blogapp/templates/blog_list.html
{% extends 'base.html' %}
{% block meta %}
<style>
    /* Adjustments for your custom styles */
    .blog-post {
        margin-bottom: 30px;
    }

    .photo-section {
        background-color: #f9f9f9;
        padding: 20px;
    }

    .photo-section img {
        max-width: 100%;
        height: auto;
        border-radius: 5px;
    }

    .blog-section {
        padding: 20px;
    }

    .search-form {
        margin-bottom: 20px;
    }

    .list-view1 .grids5-info {
        margin-bottom: 20px;
    }

    .blog-desc1 {
        font-size: 18px;
        font-weight: bold;
        color: #333;
    }

    .blog-meta {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .blog-meta .meta-item {
        display: inline-block;
        margin-right: 10px;
    }

    .meta-value {
        color: #999;
    }

</style>
{% endblock %}
{% block title %}  Blog List {% endblock %}

{% block body %}
<div class="container mb-3">
    <div class="row justify-content-end">
        <div class="col-md-4">
            <div class="mt-3">
                <form class="d-flex w-100" action="{% url 'blogapp:blogDetail' %}" method="GET">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           name="search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">

            {% for post in post %}
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <!-- Image on the left -->
                <img class="card-img-left flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
                     src="{{ post.photos.url }}"
                     alt="{{ post.title }}"
                     data-holder-rendered="true" style="width: 200px; height: 250px;">
                <div class="card-body d-flex flex-column align-items-start">
                    <strong class="d-inline-block mb-2 text-primary">{{ post.created_by }}</strong>
                    <h3 class="mb-0">
                        <a class="text-dark text-decoration-none" href="#">{{ post.title }}</a>
                    </h3>

                    <p class="card-text mb-auto">{{ post.blog|slice:":150" }}...</p>
                    <div class="mb-1 text-muted">{{ post.created.date }}</div>
                    <a href="{% url 'blogapp:fullDetail' post.id %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% empty %}
            No Record Found
            {% endfor %}
        </div>
        <div class="col-md-4">
            <div class="p-4">
                <h4 class="fst-italic">Categories</h4>
                <ul class="list-unstyled">
                    {% for category in categories %}
                    <li><a href="{% url 'blogapp:blog_list_category' category.name %}" class="text-decoration-none">{{category.name}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <h4 class="fst-italic">Recent Blog</h4>
                {% for blogs in blogs %}
                <ul class="list-unstyled">
                    <li>
                        <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top"
                           href="{% url 'blogapp:fullDetail' blogs.id%}">
                            <img src="{{blogs.photos.url}}" class="bd-placeholder-img" width="96" height="96"
                                 alt="{{ blogs.title }}">
                            <div class="col-lg-8">
                                <h6 class="mb-0"> {{blogs.title}}</h6>
                                <small class="text-body-secondary">{{blogs.created}}</small>
                            </div>
                        </a>
                    </li>
                </ul>
                {% endfor %}
            </div>
            <!-- <div class="p-4">
              <h4 class="fst-italic">Archives</h4>
              <ol class="list-unstyled mb-0">
                <li><a href="#">March 2021</a></li>
                <li><a href="#">February 2021</a></li>
              </ol>
            </div> -->
        </div>
    </div>
    <div class="container">
        <nav aria-label="Pagination">
            <ul class="pagination justify-content-center">
                {% if post.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{post.previous_page_number}}" tabindex="-1">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page=2">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page=3">3</a>
                </li>
                {% if post.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{post.next_page_number}}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>


<script>
    $('.confirm').on('click', function () {
        return confirm('Are you sure?');
    });
</script>
{%endblock%}

blogapp/templates/home.html
{% extends 'base.html' %}  {% load crispy_forms_tags %}
{% load static %}
{% block tilte %}
Home
{% endblock %}
{% block meta %}

{% endblock %}

{% block body %}

<div class="section">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/chicago.jpg'%}" class="d-block w-100" alt="...">
                <div class="carousel-caption mx-5 text-right" style='margin-bottom: 162px;'>
                    <h5>First slide label</h5>
                    <p class="lead">
                        <a href="{% url 'blogapp:blog'%}" class="btn btn-lg btn-secondary">Add Blog</a>
                    </p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/ny.jpg'%}" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p class="lead">
                        <a href="{% url 'blogapp:blog'%}" class="btn btn-lg btn-secondary">Add Blog</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/postBlog_detail.html
{% extends 'base.html' %}

{% block title %} All Blog{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 left  top">
            <div class="card-body">
                <h1> {{ object.title }}</h1>
                <p class=" text-muted">{{ request.user.username }} | {{ post.created }}</p>
                <p class="card-text ">{{ object.blog  }}</p>
            </div>
        </div>
    </div>
</div>
{%endblock%}

blogapp/templates/postblog.html
{% extends "base.html" %} {% load static %}
{% block meta %}
{% endblock %}
{% block title %}
Blogpost
{% endblock %}
{% block body %}
<div class="w-50 m-auto blogform">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="mb-3">
            <label for="sel1" class="form-label">Category</label>
            <select class="form-select" id="sel1" name="category">
                <option selected>Select</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="blog" class="form-label">Blog</label>
            <textarea class="form-control" id="blog" name="blog" rows="4" required></textarea>
        </div>
        <div class="mb-3">
            <label for="upload_plan" class="form-label">Photo</label>
            <input type="file" class="form-control" id="upload_plan" name="images" required>
        </div>
        <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>
{% endblock %}

blogapp/templates/unauthorized_access.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block body %}
<h1>Unauthorized Access</h1>
<p>You do not have permission to access this page.</p>
<p>Please make sure you are logged in with the correct account.</p>
<a href="{% url 'account_login' %}">Login</a>
{% endblock %}

blogapp/templates/update_comment.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block body %}
<div class="col-md-6 offset-md-1 offset-sm-1 col-12 mt-4 justify-content-center">
    <form method="post" enctype="multipart/form-data" action="{% url 'blogapp:updateComment' comment.id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="message" class="my-2 fw-bold">Comment</label>
            <textarea name="msg" id="message" cols="30" rows="5" class="form-control" placeholder="Leave a comment">{{ comment.comment }}</textarea>
        </div>
        <div class="form-group text-end">
            <button type="submit" class="btn btn-primary my-2">Submit</button>
        </div>
    </form>
</div>
{% endblock %}